// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Henna.png (Figma `Motif/Henna`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function HennaMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-secondary)" d="M19 3h1v1h-1zM20 4h2v2h-2zM8 5h3v2h-3zM22 5h2v3h-2zM7 6h1v4h-1zM11 6h1v1h-1zM21 6h1v1h-1zM24 6h1v4h-1zM6 7h1v4h-1zM8 7h2v1h-2zM25 7h1v5h-1zM5 8h1v4h-1zM8 8h1v1h-1zM14 8h2v1h-2zM23 8h1v1h-1zM26 8h1v3h-1zM12 9h1v1h-1zM4 10h1v2h-1zM10 10h2v1h-2zM21 10h1v2h-1zM3 12h1v1h-1zM22 12h1v1h-1zM23 14h1v2h-1zM8 16h1v2h-1zM9 19h1v1h-1zM28 19h1v1h-1zM6 20h1v5h-1zM10 20h1v2h-1zM26 20h2v2h-2zM5 21h1v3h-1zM20 21h2v1h-2zM25 21h1v4h-1zM7 22h1v4h-1zM19 22h1v1h-1zM24 22h1v4h-1zM26 22h1v2h-1zM8 23h1v4h-1zM16 23h2v1h-2zM23 23h1v4h-1zM9 24h1v3h-1zM22 24h1v3h-1zM10 25h1v3h-1zM20 25h2v1h-2zM11 26h1v2h-1zM21 26h1v1h-1zM12 28h1v1h-1z" />
      <path fill="var(--nid-accent-tertiary)" d="M12 3h5v2h-5zM11 4h1v1h-1zM17 4h1v2h-1zM14 5h3v1h-3zM18 5h1v1h-1zM17 8h1v2h-1zM18 9h2v2h-2zM20 10h1v1h-1zM10 11h1v3h-1zM19 11h1v1h-1zM27 11h1v7h-1zM9 12h1v3h-1zM11 12h1v1h-1zM28 12h1v5h-1zM5 13h1v5h-1zM4 14h1v7h-1zM8 14h1v1h-1zM26 14h1v5h-1zM3 15h1v5h-1zM22 17h2v1h-2zM21 18h2v2h-2zM20 19h1v1h-1zM12 20h1v3h-1zM21 20h1v1h-1zM11 21h1v1h-1zM13 21h1v2h-1zM14 22h1v2h-1zM13 26h5v1h-5zM14 27h7v1h-7zM15 28h5v1h-5z" />
      <path fill="var(--nid-accent-primary)" d="M13 9h4v2h-4zM12 10h1v1h-1zM21 12h1v5h-1zM15 13h2v1h-2zM22 13h1v4h-1zM9 15h2v4h-2zM13 15h1v2h-1zM18 15h1v2h-1zM15 18h2v1h-2zM10 19h1v1h-1zM15 21h5v1h-5zM15 22h4v1h-4z" />
      <path fill="var(--nid-accent-pentenary)" d="M14 14h4v4h-4z" />
    </svg>
  );
}
