// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Ikkat.png (Figma `Motif/Ikkat`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function IkkatMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-primary)" d="M14 1h4v1h-4zM13 3h1v1h-1zM18 3h1v1h-1zM11 4h2v1h-2zM19 4h2v1h-2zM10 6h1v1h-1zM21 6h1v1h-1zM8 7h2v1h-2zM22 7h2v1h-2zM7 8h1v2h-1zM24 8h1v2h-1zM6 10h1v1h-1zM25 10h1v1h-1zM4 11h1v2h-1zM27 11h1v2h-1zM3 13h1v1h-1zM15 13h2v6h-2zM28 13h1v1h-1zM1 14h1v4h-1zM14 14h1v4h-1zM17 14h1v4h-1zM30 14h1v4h-1zM13 15h1v2h-1zM18 15h1v2h-1zM3 18h1v1h-1zM28 18h1v1h-1zM4 19h1v2h-1zM27 19h1v2h-1zM6 21h1v1h-1zM25 21h1v1h-1zM7 22h1v2h-1zM24 22h1v2h-1zM8 24h2v1h-2zM22 24h2v1h-2zM10 25h1v1h-1zM21 25h1v1h-1zM11 27h2v1h-2zM19 27h2v1h-2zM13 28h1v1h-1zM18 28h1v1h-1zM14 30h4v1h-4z" />
      <path fill="var(--nid-accent-quaternary)" d="M14 4h4v2h-4zM13 6h1v2h-1zM18 6h1v2h-1zM11 7h2v2h-2zM19 7h2v2h-2zM10 9h1v2h-1zM21 9h1v2h-1zM9 10h1v1h-1zM22 10h1v1h-1zM7 11h2v2h-2zM23 11h2v2h-2zM6 13h2v1h-2zM24 13h2v1h-2zM4 14h2v4h-2zM26 14h2v4h-2zM6 18h2v1h-2zM24 18h2v1h-2zM7 19h2v2h-2zM23 19h2v2h-2zM9 21h2v1h-2zM21 21h2v1h-2zM10 22h1v1h-1zM21 22h1v1h-1zM11 23h2v2h-2zM19 23h2v2h-2zM13 24h1v2h-1zM18 24h1v2h-1zM14 26h4v2h-4z" />
      <path fill="var(--nid-accent-tertiary)" d="M14 7h4v2h-4zM13 9h1v2h-1zM18 9h1v2h-1zM11 10h2v2h-2zM19 10h2v2h-2zM10 11h1v3h-1zM21 11h1v3h-1zM11 12h1v1h-1zM20 12h1v1h-1zM9 13h1v1h-1zM22 13h1v1h-1zM7 14h2v4h-2zM23 14h2v4h-2zM9 18h2v1h-2zM21 18h2v1h-2zM10 19h2v2h-2zM20 19h2v2h-2zM12 20h1v2h-1zM19 20h1v2h-1zM11 21h1v1h-1zM13 21h1v2h-1zM18 21h1v2h-1zM20 21h1v1h-1zM14 23h4v2h-4z" />
      <path fill="var(--nid-accent-secondary)" d="M14 11h4v2h-4zM13 13h1v1h-1zM18 13h1v1h-1zM11 14h2v4h-2zM19 14h2v4h-2zM13 18h1v1h-1zM18 18h1v1h-1zM14 19h4v2h-4z" />
    </svg>
  );
}
