// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Indigo.png (Figma `Motif/Indigo`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function IndigoMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-primary)" d="M15 1h2v2h-2zM14 2h1v2h-1zM17 2h1v2h-1zM13 3h1v2h-1zM18 3h1v2h-1zM12 4h1v2h-1zM19 4h1v2h-1zM11 5h1v2h-1zM20 5h1v2h-1zM10 6h1v2h-1zM21 6h1v2h-1zM9 7h1v2h-1zM22 7h1v2h-1zM8 8h1v2h-1zM23 8h1v2h-1zM7 9h1v2h-1zM24 9h1v2h-1zM6 10h1v2h-1zM25 10h1v2h-1zM5 11h1v2h-1zM26 11h1v2h-1zM4 12h1v2h-1zM27 12h1v2h-1zM3 13h1v2h-1zM28 13h1v2h-1zM2 14h1v4h-1zM29 14h1v4h-1zM1 15h1v2h-1zM30 15h1v2h-1zM3 17h1v2h-1zM28 17h1v2h-1zM4 18h1v2h-1zM27 18h1v2h-1zM5 19h1v2h-1zM26 19h1v2h-1zM6 20h1v2h-1zM25 20h1v2h-1zM7 21h1v2h-1zM24 21h1v2h-1zM8 22h1v2h-1zM23 22h1v2h-1zM9 23h1v2h-1zM22 23h1v2h-1zM10 24h1v2h-1zM21 24h1v2h-1zM11 25h1v2h-1zM20 25h1v2h-1zM12 26h1v2h-1zM19 26h1v2h-1zM13 27h1v2h-1zM18 27h1v2h-1zM14 28h1v2h-1zM17 28h1v2h-1zM15 29h2v2h-2z" />
      <path fill="var(--nid-accent-tertiary)" d="M15 5h2v2h-2zM14 6h1v2h-1zM17 6h1v2h-1zM13 7h1v2h-1zM18 7h1v2h-1zM12 8h1v2h-1zM19 8h1v2h-1zM11 9h1v2h-1zM20 9h1v2h-1zM10 10h1v2h-1zM21 10h1v2h-1zM9 11h1v2h-1zM22 11h1v2h-1zM8 12h1v2h-1zM23 12h1v2h-1zM7 13h1v2h-1zM24 13h1v2h-1zM6 14h1v4h-1zM25 14h1v4h-1zM5 15h1v2h-1zM26 15h1v2h-1zM7 17h1v2h-1zM24 17h1v2h-1zM8 18h1v2h-1zM23 18h1v2h-1zM9 19h1v2h-1zM22 19h1v2h-1zM10 20h1v2h-1zM21 20h1v2h-1zM11 21h1v2h-1zM20 21h1v2h-1zM12 22h1v2h-1zM19 22h1v2h-1zM13 23h1v2h-1zM18 23h1v2h-1zM14 24h1v2h-1zM17 24h1v2h-1zM15 25h2v2h-2z" />
      <path fill="var(--nid-accent-secondary)" d="M15 9h2v2h-2zM14 10h1v2h-1zM17 10h1v2h-1zM13 11h1v2h-1zM18 11h1v2h-1zM12 12h1v2h-1zM19 12h1v2h-1zM11 13h1v2h-1zM20 13h1v2h-1zM10 14h1v4h-1zM21 14h1v4h-1zM9 15h1v2h-1zM22 15h1v2h-1zM11 17h1v2h-1zM20 17h1v2h-1zM12 18h1v2h-1zM19 18h1v2h-1zM13 19h1v2h-1zM18 19h1v2h-1zM14 20h1v2h-1zM17 20h1v2h-1zM15 21h2v2h-2z" />
      <path fill="var(--nid-accent-pentenary)" d="M15 13h2v2h-2zM14 14h1v4h-1zM17 14h1v4h-1zM13 15h1v2h-1zM18 15h1v2h-1zM15 17h2v2h-2z" />
    </svg>
  );
}
