// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Khadi.png (Figma `Motif/Khadi`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function KhadiMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-tertiary)" d="M6 4h2v8h-2zM12 4h2v2h-2zM18 4h2v8h-2zM24 4h2v2h-2zM12 8h2v10h-2zM24 8h2v10h-2zM6 14h2v10h-2zM18 14h2v10h-2zM12 20h2v8h-2zM24 20h2v8h-2zM6 26h2v2h-2zM18 26h2v2h-2z" />
      <path fill="var(--nid-accent-primary)" d="M4 6h2v2h-2zM8 6h10v2h-10zM20 6h8v2h-8zM4 12h8v2h-8zM14 12h10v2h-10zM26 12h2v2h-2zM4 18h2v2h-2zM8 18h10v2h-10zM20 18h8v2h-8zM4 24h8v2h-8zM14 24h10v2h-10zM26 24h2v2h-2z" />
    </svg>
  );
}
