// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Lotus.png (Figma `Motif/Lotus`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function LotusMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-secondary)" d="M15 4h2v4h-2zM14 5h1v3h-1zM17 5h1v3h-1zM8 7h3v3h-3zM13 7h1v1h-1zM18 7h1v1h-1zM21 7h3v3h-3zM7 8h1v3h-1zM11 8h1v1h-1zM20 8h1v1h-1zM24 8h1v3h-1zM8 10h2v1h-2zM22 10h2v1h-2zM8 11h1v1h-1zM23 11h1v1h-1zM7 13h1v6h-1zM24 13h1v6h-1zM5 14h2v4h-2zM25 14h2v4h-2zM4 15h1v2h-1zM27 15h1v2h-1zM8 20h1v5h-1zM23 20h1v5h-1zM7 21h1v3h-1zM9 21h1v4h-1zM22 21h1v4h-1zM24 21h1v3h-1zM10 22h1v3h-1zM21 22h1v3h-1zM11 23h1v1h-1zM20 23h1v1h-1zM13 24h6v1h-6zM14 25h4v2h-4zM15 27h2v1h-2z" />
      <path fill="var(--nid-accent-primary)" d="M13 8h6v1h-6zM11 9h2v4h-2zM14 9h4v2h-4zM19 9h2v4h-2zM10 10h1v3h-1zM21 10h1v3h-1zM9 11h1v2h-1zM15 11h2v1h-2zM22 11h1v2h-1zM8 13h1v6h-1zM13 13h1v1h-1zM18 13h1v1h-1zM23 13h1v6h-1zM9 14h2v4h-2zM21 14h2v4h-2zM11 15h1v2h-1zM20 15h1v2h-1zM13 18h1v1h-1zM18 18h1v1h-1zM9 19h4v2h-4zM19 19h4v2h-4zM15 20h2v4h-2zM10 21h3v1h-3zM14 21h1v3h-1zM17 21h1v3h-1zM19 21h3v1h-3zM11 22h2v1h-2zM19 22h2v1h-2zM13 23h1v1h-1zM18 23h1v1h-1z" />
      <path fill="var(--nid-accent-tertiary)" d="M13 9h1v4h-1zM18 9h1v4h-1zM14 11h1v2h-1zM17 11h1v2h-1zM9 13h4v1h-4zM19 13h4v1h-4zM11 14h2v1h-2zM19 14h2v1h-2zM11 17h2v2h-2zM19 17h2v2h-2zM9 18h2v1h-2zM21 18h2v1h-2zM13 19h2v2h-2zM17 19h2v2h-2zM13 21h1v2h-1zM18 21h1v2h-1z" />
      <path fill="var(--nid-accent-pentenary)" d="M15 14h2v4h-2zM14 15h1v2h-1zM17 15h1v2h-1z" />
    </svg>
  );
}
