// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Peacock.png (Figma `Motif/Peacock`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function PeacockMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-secondary)" d="M13 3h6v2h-6zM8 5h1v2h-1zM23 5h1v2h-1zM6 6h2v2h-2zM9 6h1v1h-1zM22 6h1v1h-1zM24 6h2v2h-2zM5 8h2v1h-2zM25 8h2v1h-2zM6 9h1v1h-1zM25 9h1v1h-1zM3 13h2v6h-2zM27 13h2v6h-2zM6 22h1v4h-1zM25 22h1v4h-1zM5 23h1v1h-1zM26 23h1v1h-1zM7 24h1v2h-1zM24 24h1v2h-1zM8 25h2v1h-2zM22 25h2v1h-2zM8 26h1v1h-1zM23 26h1v1h-1zM13 27h6v2h-6z" />
      <path fill="var(--nid-accent-primary)" d="M15 5h1v4h-1zM14 6h1v2h-1zM9 8h2v2h-2zM11 9h1v1h-1zM22 9h2v2h-2zM10 10h1v1h-1zM21 10h1v1h-1zM22 11h1v1h-1zM24 14h2v2h-2zM23 15h1v1h-1zM26 15h1v1h-1zM5 16h4v1h-4zM6 17h2v1h-2zM9 20h1v3h-1zM8 21h1v2h-1zM10 21h1v1h-1zM21 21h1v3h-1zM20 22h1v1h-1zM22 22h1v2h-1zM16 23h1v4h-1zM17 24h1v2h-1z" />
      <path fill="var(--nid-accent-quaternary)" d="M14 10h4v1h-4zM11 11h2v2h-2zM15 11h2v1h-2zM19 11h2v2h-2zM13 12h1v1h-1zM18 12h1v1h-1zM12 13h1v1h-1zM19 13h1v1h-1zM10 14h1v4h-1zM21 14h1v4h-1zM11 15h1v2h-1zM20 15h1v2h-1zM12 18h1v3h-1zM19 18h1v3h-1zM11 19h1v2h-1zM13 19h1v1h-1zM18 19h1v1h-1zM20 19h1v2h-1zM15 20h2v2h-2zM14 21h1v1h-1zM17 21h1v1h-1z" />
      <path fill="var(--nid-accent-tertiary)" d="M16 5h1v4h-1zM17 6h1v2h-1zM21 8h2v1h-2zM8 9h1v2h-1zM20 9h2v1h-2zM9 10h1v2h-1zM6 14h2v2h-2zM5 15h1v1h-1zM8 15h1v1h-1zM23 16h4v1h-4zM24 17h2v1h-2zM22 20h1v2h-1zM23 21h1v2h-1zM10 22h2v1h-2zM9 23h2v1h-2zM15 23h1v4h-1zM14 24h1v2h-1z" />
      <path fill="var(--nid-accent-pentenary)" d="M15 13h2v6h-2zM14 14h1v4h-1zM17 14h1v4h-1zM13 15h1v2h-1zM18 15h1v2h-1z" />
    </svg>
  );
}
