// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Terracotta.png (Figma `Motif/Terracotta`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function TerracottaMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-tertiary)" d="M14 5h4v5h-4zM8 8h2v2h-2zM22 8h2v2h-2zM10 9h1v3h-1zM21 9h1v3h-1zM9 10h1v1h-1zM11 10h1v2h-1zM20 10h1v2h-1zM22 10h1v1h-1zM5 14h5v4h-5zM22 14h5v4h-5zM10 20h2v2h-2zM20 20h2v2h-2zM9 21h1v3h-1zM22 21h1v3h-1zM8 22h1v2h-1zM10 22h1v1h-1zM14 22h4v5h-4zM21 22h1v1h-1zM23 22h1v2h-1z" />
      <path fill="var(--nid-accent-secondary)" d="M14 3h4v2h-4zM7 6h1v3h-1zM24 6h1v3h-1zM6 7h1v1h-1zM8 7h1v1h-1zM23 7h1v1h-1zM25 7h1v1h-1zM3 14h2v4h-2zM27 14h2v4h-2zM7 23h1v3h-1zM24 23h1v3h-1zM6 24h1v1h-1zM8 24h1v1h-1zM23 24h1v1h-1zM25 24h1v1h-1zM14 27h4v2h-4z" />
      <path fill="var(--nid-accent-primary)" d="M14 11h4v2h-4zM12 12h2v2h-2zM18 12h2v2h-2zM11 14h2v4h-2zM19 14h2v4h-2zM12 18h2v2h-2zM18 18h2v2h-2zM14 19h4v2h-4z" />
      <path fill="var(--nid-accent-pentenary)" d="M14 13h4v6h-4zM13 14h1v4h-1zM18 14h1v4h-1z" />
    </svg>
  );
}
