// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Tiger.png (Figma `Motif/Tiger`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function TigerMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-secondary)" d="M12 3h2v2h-2zM16 3h3v3h-3zM10 4h2v15h-2zM15 4h1v12h-1zM12 5h1v24h-1zM22 5h2v22h-2zM7 6h1v4h-1zM16 6h2v22h-2zM24 6h1v3h-1zM6 7h1v18h-1zM9 7h1v9h-1zM14 7h1v5h-1zM21 7h1v21h-1zM5 8h1v15h-1zM26 8h1v16h-1zM20 9h1v11h-1zM4 10h1v10h-1zM18 10h1v15h-1zM25 10h1v2h-1zM27 10h1v12h-1zM3 12h1v5h-1zM28 12h1v8h-1zM19 13h1v9h-1zM13 15h1v13h-1zM7 18h1v8h-1zM11 19h1v9h-1zM14 19h1v6h-1zM24 19h1v7h-1zM8 21h1v6h-1zM15 22h1v7h-1zM10 27h1v1h-1zM14 27h1v1h-1zM16 28h1v1h-1z" />
      <path fill="var(--nid-quaternary-650)" d="M14 3h2v1h-2zM19 3h1v10h-1zM14 4h1v3h-1zM20 4h2v3h-2zM8 5h2v2h-2zM13 5h1v10h-1zM18 6h1v4h-1zM8 7h1v14h-1zM20 7h1v2h-1zM25 7h1v3h-1zM24 9h1v10h-1zM7 10h1v8h-1zM14 12h1v7h-1zM25 12h1v13h-1zM9 16h1v11h-1zM15 16h1v6h-1zM3 17h1v3h-1zM10 19h1v8h-1zM4 20h1v2h-1zM20 20h1v8h-1zM19 22h1v7h-1zM5 23h1v1h-1zM14 25h1v2h-1zM18 25h1v4h-1zM13 28h2v1h-2zM17 28h1v1h-1z" />
    </svg>
  );
}
