// GENERATED by scripts/generate-motifs.py - do not edit by hand.
// Source: design/assets/motifs/Yoga.png (Figma `Motif/Yoga`).
// Regenerate with `npm run generate:motifs`.
import type { MotifProps } from "@/components/header/motifs";

export function YogaMotif({ className }: MotifProps) {
  return (
    <svg viewBox="0 0 32 32" className={className} focusable="false">
      <path fill="var(--nid-accent-secondary)" d="M15 5h2v2h-2zM9 8h1v2h-1zM22 8h1v2h-1zM8 9h1v1h-1zM23 9h1v1h-1zM5 15h2v2h-2zM25 15h2v2h-2zM8 22h2v1h-2zM22 22h2v1h-2zM9 23h1v1h-1zM22 23h1v1h-1zM15 25h2v2h-2z" />
      <path fill="var(--nid-accent-tertiary)" d="M15 10h1v2h-1zM19 11h1v2h-1zM11 12h2v1h-2zM20 15h2v1h-2zM10 16h2v1h-2zM12 19h1v2h-1zM19 19h2v1h-2zM16 20h1v2h-1z" />
      <path fill="var(--nid-accent-primary)" d="M15 14h2v4h-2zM14 15h1v2h-1zM17 15h1v2h-1z" />
    </svg>
  );
}
