// GENERATED by scripts/generate-patterns.py - do not edit by hand.
// Regenerate with `npm run generate:patterns`.

export interface PatternFieldProps {
  className?: string;
}

export function PatternField1({ className }: PatternFieldProps) {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 324 324"
      preserveAspectRatio="xMidYMid slice"
      className={className}
    >
      <defs>
        <g id="nid-patternfield1-f0">
          <path fill="var(--nid-accent-quaternary)" d="M2 24h2v2h-2zM4 14h2v2h-2zM4 22h2v2h-2zM6 16h2v2h-2zM8 18h2v2h-2zM14 42h2v2h-2zM16 40h2v2h-2zM18 38h2v2h-2zM20 22h2v4h-2zM22 2h2v2h-2zM22 20h4v2h-4zM22 26h4v2h-4zM22 42h2v2h-2zM24 4h2v2h-2zM24 44h2v2h-2zM26 22h2v4h-2zM28 8h2v2h-2zM30 6h2v2h-2zM32 4h2v2h-2zM38 28h2v2h-2zM40 30h2v2h-2zM42 24h2v2h-2zM42 32h2v2h-2zM44 22h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M2 12h2v2h-2zM8 10h2v2h-2zM10 20h2v2h-2zM10 38h2v2h-2zM12 44h2v2h-2zM16 26h2v2h-2zM18 18h2v2h-2zM18 28h2v2h-2zM20 16h2v2h-2zM20 36h2v2h-2zM26 10h2v2h-2zM26 30h2v2h-2zM28 18h2v2h-2zM28 28h2v2h-2zM30 20h2v2h-2zM34 2h2v2h-2zM36 8h2v2h-2zM36 26h2v2h-2zM38 36h2v2h-2zM44 34h2v2h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M4 26h2v2h-2zM6 24h2v2h-2zM12 22h2v2h-2zM14 24h2v2h-2zM20 4h2v2h-2zM22 6h2v2h-2zM22 14h2v2h-2zM22 34h2v2h-2zM24 12h2v2h-2zM24 32h2v2h-2zM24 40h2v2h-2zM26 42h2v2h-2zM32 22h2v2h-2zM34 24h2v2h-2zM40 22h2v2h-2zM42 20h2v2h-2z" />
        </g>
        <g id="nid-patternfield1-f1">
          <path fill="var(--nid-accent-tertiary)" d="M2 22h2v4h-2zM4 14h2v2h-2zM6 16h2v2h-2zM8 18h2v2h-2zM14 42h2v2h-2zM16 18h2v2h-2zM16 40h2v2h-2zM18 30h2v2h-2zM18 38h2v2h-2zM20 22h2v4h-2zM22 2h4v2h-4zM22 20h4v2h-4zM22 26h4v2h-4zM22 44h4v2h-4zM26 22h2v4h-2zM28 8h2v2h-2zM28 16h2v2h-2zM30 6h2v2h-2zM30 28h2v2h-2zM32 4h2v2h-2zM38 28h2v2h-2zM40 30h2v2h-2zM42 32h2v2h-2zM44 22h2v4h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M2 12h2v2h-2zM4 28h2v2h-2zM8 8h2v2h-2zM8 38h2v2h-2zM10 20h2v2h-2zM12 44h2v2h-2zM16 26h2v2h-2zM18 4h2v2h-2zM20 16h2v2h-2zM20 36h2v2h-2zM26 10h2v2h-2zM26 30h2v2h-2zM28 42h2v2h-2zM30 20h2v2h-2zM34 2h2v2h-2zM36 26h2v2h-2zM38 8h2v2h-2zM38 38h2v2h-2zM42 18h2v2h-2zM44 34h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M6 24h2v2h-2zM12 22h2v4h-2zM14 24h2v2h-2zM22 6h2v2h-2zM22 12h4v2h-4zM22 14h2v2h-2zM22 34h4v2h-4zM24 32h2v2h-2zM24 40h2v2h-2zM32 22h4v2h-4zM34 24h2v2h-2zM40 22h2v2h-2z" />
        </g>
        <g id="nid-patternfield1-f2">
          <path fill="var(--nid-accent-quaternary)" d="M0 22h2v4h-2zM2 12h2v2h-2zM4 28h2v2h-2zM8 10h2v2h-2zM10 20h2v2h-2zM10 38h2v2h-2zM12 44h2v2h-2zM16 20h2v2h-2zM16 26h2v2h-2zM18 4h2v2h-2zM20 16h2v2h-2zM20 30h2v2h-2zM20 36h2v2h-2zM22 0h4v2h-4zM22 46h4v2h-4zM26 10h2v2h-2zM26 16h2v2h-2zM26 30h2v2h-2zM28 42h2v2h-2zM30 20h2v2h-2zM30 26h2v2h-2zM34 2h2v2h-2zM36 8h2v2h-2zM36 26h2v2h-2zM38 36h2v2h-2zM42 18h2v2h-2zM44 34h2v2h-2zM46 22h2v4h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M4 14h2v2h-2zM6 16h2v2h-2zM8 18h2v2h-2zM14 42h2v2h-2zM16 40h2v2h-2zM18 38h2v2h-2zM20 22h2v4h-2zM22 20h4v2h-4zM22 26h4v2h-4zM26 22h2v4h-2zM28 8h2v2h-2zM30 6h2v2h-2zM32 4h2v2h-2zM38 28h2v2h-2zM40 30h2v2h-2zM42 32h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M8 24h2v2h-2zM12 22h2v2h-2zM14 24h2v2h-2zM22 8h2v2h-2zM22 14h2v2h-2zM22 34h2v2h-2zM24 12h2v2h-2zM24 32h2v2h-2zM24 38h2v2h-2zM32 22h2v2h-2zM34 24h2v2h-2zM38 22h2v2h-2z" />
        </g>
        <g id="nid-patternfield1-f3">
          <path fill="var(--nid-accent-secondary)" d="M2 26h4v2h-4zM4 20h2v2h-2zM6 10h2v2h-2zM8 24h2v2h-2zM10 40h2v2h-2zM12 22h2v2h-2zM14 24h2v2h-2zM18 20h2v2h-2zM20 2h2v4h-2zM20 28h2v2h-2zM20 42h2v2h-2zM22 8h2v2h-2zM22 14h2v2h-2zM22 34h2v2h-2zM24 12h2v2h-2zM24 32h2v2h-2zM24 38h2v2h-2zM26 4h2v2h-2zM26 18h2v2h-2zM26 42h2v4h-2zM28 26h2v2h-2zM32 22h2v2h-2zM34 24h2v2h-2zM36 6h2v2h-2zM38 22h2v2h-2zM40 36h2v2h-2zM42 20h4v2h-4zM42 26h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M4 14h2v2h-2zM6 16h2v2h-2zM8 18h2v2h-2zM14 42h2v2h-2zM16 40h2v2h-2zM18 38h2v2h-2zM20 22h2v4h-2zM22 20h4v2h-4zM22 26h4v2h-4zM26 22h2v4h-2zM28 8h2v2h-2zM30 6h2v2h-2zM32 4h2v2h-2zM38 28h2v2h-2zM40 30h2v2h-2zM42 32h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M2 12h2v2h-2zM10 20h2v2h-2zM12 44h2v2h-2zM16 26h2v2h-2zM20 16h2v2h-2zM20 36h2v2h-2zM26 10h2v2h-2zM26 30h2v2h-2zM30 20h2v2h-2zM34 2h2v2h-2zM36 26h2v2h-2zM44 34h2v2h-2z" />
        </g>
      </defs>
        <g className="nid-pattern-unit" transform="translate(0 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield1-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield1-f3" className="nid-pattern-frame" />
          </g>
        </g>
    </svg>
  );
}

export function PatternField2({ className }: PatternFieldProps) {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 324 324"
      preserveAspectRatio="xMidYMid slice"
      className={className}
    >
      <defs>
        <g id="nid-patternfield2-f0">
          <path fill="var(--nid-accent-tertiary)" d="M0 0h2v2h-2zM0 46h2v2h-2zM2 20h2v2h-2zM2 26h2v2h-2zM4 4h2v2h-2zM4 42h2v2h-2zM6 6h2v2h-2zM6 40h2v2h-2zM8 14h2v2h-2zM8 32h2v2h-2zM10 16h2v2h-2zM10 30h2v2h-2zM14 8h2v2h-2zM14 38h2v2h-2zM16 10h2v2h-2zM16 16h2v2h-2zM16 30h2v2h-2zM16 36h2v2h-2zM18 18h2v2h-2zM18 28h2v2h-2zM20 2h2v2h-2zM20 44h2v2h-2zM22 22h4v4h-4zM26 2h2v2h-2zM26 44h2v2h-2zM28 18h2v2h-2zM28 28h2v2h-2zM30 10h2v2h-2zM30 16h2v2h-2zM30 30h2v2h-2zM30 36h2v2h-2zM32 8h2v2h-2zM32 38h2v2h-2zM36 16h2v2h-2zM36 30h2v2h-2zM38 14h2v2h-2zM38 32h2v2h-2zM40 6h2v2h-2zM40 40h2v2h-2zM42 4h2v2h-2zM42 42h2v2h-2zM44 20h2v2h-2zM44 26h2v2h-2zM46 0h2v2h-2zM46 46h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M0 24h2v2h-2zM2 40h2v2h-2zM6 2h2v2h-2zM8 28h2v2h-2zM10 12h2v2h-2zM10 26h2v2h-2zM12 36h2v2h-2zM14 28h2v2h-2zM18 8h2v2h-2zM18 14h2v2h-2zM20 10h2v2h-2zM22 0h2v2h-2zM24 46h2v2h-2zM26 36h2v2h-2zM28 32h2v2h-2zM28 38h2v2h-2zM32 18h2v2h-2zM34 10h2v2h-2zM36 20h2v2h-2zM36 34h2v2h-2zM38 18h2v2h-2zM40 44h2v2h-2zM44 6h2v2h-2zM46 22h2v2h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M0 22h2v2h-2zM2 6h2v2h-2zM6 44h2v2h-2zM8 18h2v2h-2zM10 20h2v2h-2zM10 34h2v2h-2zM12 10h2v2h-2zM14 18h2v2h-2zM18 32h2v2h-2zM18 38h2v2h-2zM20 36h2v2h-2zM22 46h2v2h-2zM24 0h2v2h-2zM26 10h2v2h-2zM28 8h2v2h-2zM28 14h2v2h-2zM32 28h2v2h-2zM34 36h2v2h-2zM36 12h2v2h-2zM36 26h2v2h-2zM38 28h2v2h-2zM40 2h2v2h-2zM44 40h2v2h-2zM46 24h2v2h-2z" />
        </g>
        <g id="nid-patternfield2-f1">
          <path fill="var(--nid-accent-secondary)" d="M0 0h2v2h-2zM0 46h2v2h-2zM2 2h2v2h-2zM2 20h2v2h-2zM2 26h2v2h-2zM2 44h2v2h-2zM6 6h2v2h-2zM6 40h2v2h-2zM10 16h2v2h-2zM10 30h2v2h-2zM16 10h2v2h-2zM16 16h2v2h-2zM16 30h2v2h-2zM16 36h2v2h-2zM18 18h2v2h-2zM18 28h2v2h-2zM20 2h2v2h-2zM20 44h2v2h-2zM22 22h4v4h-4zM26 2h2v2h-2zM26 44h2v2h-2zM28 18h2v2h-2zM28 28h2v2h-2zM30 10h2v2h-2zM30 16h2v2h-2zM30 30h2v2h-2zM30 36h2v2h-2zM36 16h2v2h-2zM36 30h2v2h-2zM40 6h2v2h-2zM40 40h2v2h-2zM44 2h2v2h-2zM44 20h2v2h-2zM44 26h2v2h-2zM44 44h2v2h-2zM46 0h2v2h-2zM46 46h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M0 24h2v2h-2zM2 40h2v2h-2zM6 2h2v2h-2zM6 14h2v2h-2zM8 28h2v2h-2zM10 12h2v2h-2zM10 26h2v2h-2zM12 36h2v2h-2zM14 28h2v2h-2zM14 40h2v2h-2zM18 8h2v2h-2zM18 14h2v2h-2zM20 10h2v2h-2zM22 0h2v2h-2zM24 46h2v2h-2zM26 36h2v2h-2zM28 32h2v2h-2zM28 38h2v2h-2zM32 6h2v2h-2zM32 18h2v2h-2zM34 10h2v2h-2zM36 20h2v2h-2zM36 34h2v2h-2zM38 18h2v2h-2zM40 32h2v2h-2zM40 44h2v2h-2zM44 6h2v2h-2zM46 22h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M0 22h2v2h-2zM2 6h2v2h-2zM6 32h2v2h-2zM6 44h2v2h-2zM8 18h2v2h-2zM10 20h2v2h-2zM10 34h2v2h-2zM12 10h2v2h-2zM14 6h2v2h-2zM14 18h2v2h-2zM18 32h2v2h-2zM18 38h2v2h-2zM20 36h2v2h-2zM22 46h2v2h-2zM24 0h2v2h-2zM26 10h2v2h-2zM28 8h2v2h-2zM28 14h2v2h-2zM32 28h2v2h-2zM32 40h2v2h-2zM34 36h2v2h-2zM36 12h2v2h-2zM36 26h2v2h-2zM38 28h2v2h-2zM40 2h2v2h-2zM40 14h2v2h-2zM44 40h2v2h-2zM46 24h2v2h-2z" />
        </g>
        <g id="nid-patternfield2-f2">
          <path fill="var(--nid-accent-tertiary)" d="M0 22h2v2h-2zM2 6h2v2h-2zM2 30h2v2h-2zM4 14h2v2h-2zM6 44h2v2h-2zM8 18h2v2h-2zM10 20h2v2h-2zM10 34h2v2h-2zM12 10h2v2h-2zM14 18h2v2h-2zM14 42h2v2h-2zM16 2h2v2h-2zM18 32h2v2h-2zM18 38h2v2h-2zM20 36h2v2h-2zM22 46h2v2h-2zM24 0h2v2h-2zM26 10h2v2h-2zM28 8h2v2h-2zM28 14h2v2h-2zM30 44h2v2h-2zM32 4h2v2h-2zM32 28h2v2h-2zM34 36h2v2h-2zM36 12h2v2h-2zM36 26h2v2h-2zM38 28h2v2h-2zM40 2h2v2h-2zM42 32h2v2h-2zM44 16h2v2h-2zM44 40h2v2h-2zM46 24h2v2h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M0 24h2v2h-2zM2 16h2v2h-2zM2 40h2v2h-2zM4 32h2v2h-2zM6 2h2v2h-2zM8 28h2v2h-2zM10 12h2v2h-2zM10 26h2v2h-2zM12 36h2v2h-2zM14 4h2v2h-2zM14 28h2v2h-2zM16 44h2v2h-2zM18 8h2v2h-2zM18 14h2v2h-2zM20 10h2v2h-2zM22 0h2v2h-2zM24 46h2v2h-2zM26 36h2v2h-2zM28 32h2v2h-2zM28 38h2v2h-2zM30 2h2v2h-2zM32 18h2v2h-2zM32 42h2v2h-2zM34 10h2v2h-2zM36 20h2v2h-2zM36 34h2v2h-2zM38 18h2v2h-2zM40 44h2v2h-2zM42 14h2v2h-2zM44 6h2v2h-2zM44 30h2v2h-2zM46 22h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M0 0h2v2h-2zM0 46h2v2h-2zM2 2h2v2h-2zM2 44h2v2h-2zM8 8h2v2h-2zM8 38h2v2h-2zM10 16h2v2h-2zM10 30h2v2h-2zM16 10h2v2h-2zM16 16h2v2h-2zM16 30h2v2h-2zM16 36h2v2h-2zM20 20h2v2h-2zM20 26h2v2h-2zM22 22h4v4h-4zM26 20h2v2h-2zM26 26h2v2h-2zM30 10h2v2h-2zM30 16h2v2h-2zM30 30h2v2h-2zM30 36h2v2h-2zM36 16h2v2h-2zM36 30h2v2h-2zM38 8h2v2h-2zM38 38h2v2h-2zM44 2h2v2h-2zM44 44h2v2h-2zM46 0h2v2h-2zM46 46h2v2h-2z" />
        </g>
        <g id="nid-patternfield2-f3">
          <path fill="var(--nid-accent-tertiary)" d="M0 0h2v2h-2zM0 46h2v2h-2zM2 2h2v2h-2zM2 8h2v2h-2zM2 38h2v2h-2zM2 44h2v2h-2zM8 2h2v2h-2zM8 8h2v2h-2zM8 20h2v2h-2zM8 26h2v2h-2zM8 38h2v2h-2zM8 44h2v2h-2zM10 16h2v2h-2zM10 30h2v2h-2zM16 10h2v2h-2zM16 36h2v2h-2zM18 18h2v2h-2zM18 28h2v2h-2zM20 8h2v2h-2zM20 20h2v2h-2zM20 26h2v2h-2zM20 38h2v2h-2zM22 22h4v4h-4zM26 8h2v2h-2zM26 20h2v2h-2zM26 26h2v2h-2zM26 38h2v2h-2zM28 18h2v2h-2zM28 28h2v2h-2zM30 10h2v2h-2zM30 36h2v2h-2zM36 16h2v2h-2zM36 30h2v2h-2zM38 2h2v2h-2zM38 8h2v2h-2zM38 20h2v2h-2zM38 26h2v2h-2zM38 38h2v2h-2zM38 44h2v2h-2zM44 2h2v2h-2zM44 8h2v2h-2zM44 38h2v2h-2zM44 44h2v2h-2zM46 0h2v2h-2zM46 46h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M0 20h2v2h-2zM2 16h2v2h-2zM4 32h2v2h-2zM8 28h2v2h-2zM10 12h2v2h-2zM12 36h2v2h-2zM14 4h2v2h-2zM14 28h2v2h-2zM16 44h2v2h-2zM18 8h2v2h-2zM18 14h2v2h-2zM20 46h2v2h-2zM26 0h2v2h-2zM28 32h2v2h-2zM28 38h2v2h-2zM30 2h2v2h-2zM32 18h2v2h-2zM32 42h2v2h-2zM34 10h2v2h-2zM36 34h2v2h-2zM38 18h2v2h-2zM42 14h2v2h-2zM44 30h2v2h-2zM46 26h2v2h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M0 26h2v2h-2zM2 30h2v2h-2zM4 14h2v2h-2zM8 18h2v2h-2zM10 34h2v2h-2zM12 10h2v2h-2zM14 18h2v2h-2zM14 42h2v2h-2zM16 2h2v2h-2zM18 32h2v2h-2zM18 38h2v2h-2zM20 0h2v2h-2zM26 46h2v2h-2zM28 8h2v2h-2zM28 14h2v2h-2zM30 44h2v2h-2zM32 4h2v2h-2zM32 28h2v2h-2zM34 36h2v2h-2zM36 12h2v2h-2zM38 28h2v2h-2zM42 32h2v2h-2zM44 16h2v2h-2zM46 20h2v2h-2z" />
        </g>
      </defs>
        <g className="nid-pattern-unit" transform="translate(0 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield2-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield2-f3" className="nid-pattern-frame" />
          </g>
        </g>
    </svg>
  );
}

export function PatternField3({ className }: PatternFieldProps) {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 324 324"
      preserveAspectRatio="xMidYMid slice"
      className={className}
    >
      <defs>
        <g id="nid-patternfield3-f0">
          <path fill="var(--nid-accent-secondary)" d="M4 18h2v2h-2zM4 28h2v2h-2zM6 16h2v2h-2zM6 30h2v2h-2zM8 8h2v2h-2zM8 14h2v2h-2zM8 32h2v2h-2zM8 38h2v2h-2zM14 8h2v2h-2zM14 38h2v2h-2zM16 6h2v2h-2zM16 18h2v2h-2zM16 28h2v2h-2zM16 40h2v2h-2zM18 4h2v2h-2zM18 16h2v2h-2zM18 30h2v2h-2zM18 42h2v2h-2zM28 4h2v2h-2zM28 16h2v2h-2zM28 30h2v2h-2zM28 42h2v2h-2zM30 6h2v2h-2zM30 18h2v2h-2zM30 28h2v2h-2zM30 40h2v2h-2zM32 8h2v2h-2zM32 38h2v2h-2zM38 8h2v2h-2zM38 14h2v2h-2zM38 32h2v2h-2zM38 38h2v2h-2zM40 16h2v2h-2zM40 30h2v2h-2zM42 18h2v2h-2zM42 28h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M4 4h2v2h-2zM4 42h2v2h-2zM6 20h2v2h-2zM6 26h2v2h-2zM18 20h2v2h-2zM18 26h2v2h-2zM20 6h2v2h-2zM20 18h2v2h-2zM20 28h2v2h-2zM20 40h2v2h-2zM26 6h2v2h-2zM26 18h2v2h-2zM26 28h2v2h-2zM26 40h2v2h-2zM28 20h2v2h-2zM28 26h2v2h-2zM40 20h2v2h-2zM40 26h2v2h-2zM42 4h2v2h-2zM42 42h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M8 22h2v4h-2zM14 16h2v2h-2zM14 22h2v4h-2zM14 30h2v2h-2zM16 14h2v2h-2zM16 32h2v2h-2zM20 22h2v4h-2zM22 8h4v2h-4zM22 14h4v2h-4zM22 20h4v2h-4zM22 26h4v2h-4zM22 32h4v2h-4zM22 38h4v2h-4zM26 22h2v4h-2zM30 14h2v2h-2zM30 32h2v2h-2zM32 16h2v2h-2zM32 22h2v4h-2zM32 30h2v2h-2zM38 22h2v4h-2z" />
        </g>
        <g id="nid-patternfield3-f1">
          <path fill="var(--nid-accent-secondary)" d="M2 12h2v2h-2zM2 34h2v2h-2zM4 4h2v2h-2zM4 22h2v4h-2zM4 42h2v2h-2zM10 10h2v2h-2zM10 36h2v2h-2zM12 2h2v2h-2zM12 44h2v2h-2zM18 20h2v2h-2zM18 26h2v2h-2zM20 18h2v2h-2zM20 28h2v2h-2zM22 4h4v2h-4zM22 42h4v2h-4zM26 18h2v2h-2zM26 28h2v2h-2zM28 20h2v2h-2zM28 26h2v2h-2zM34 2h2v2h-2zM34 44h2v2h-2zM36 10h2v2h-2zM36 36h2v2h-2zM42 4h2v2h-2zM42 22h2v4h-2zM42 42h2v2h-2zM44 12h2v2h-2zM44 34h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M4 18h2v2h-2zM4 28h2v2h-2zM8 14h2v2h-2zM8 32h2v2h-2zM14 8h2v2h-2zM14 22h2v4h-2zM14 38h2v2h-2zM16 18h2v2h-2zM16 28h2v2h-2zM18 4h2v2h-2zM18 16h2v2h-2zM18 30h2v2h-2zM18 42h2v2h-2zM22 14h4v2h-4zM22 32h4v2h-4zM28 4h2v2h-2zM28 16h2v2h-2zM28 30h2v2h-2zM28 42h2v2h-2zM30 18h2v2h-2zM30 28h2v2h-2zM32 8h2v2h-2zM32 22h2v4h-2zM32 38h2v2h-2zM38 14h2v2h-2zM38 32h2v2h-2zM42 18h2v2h-2zM42 28h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M8 22h2v4h-2zM14 16h2v2h-2zM14 30h2v2h-2zM16 14h2v2h-2zM16 32h2v2h-2zM20 22h2v4h-2zM22 8h4v2h-4zM22 20h4v2h-4zM22 26h4v2h-4zM22 38h4v2h-4zM26 22h2v4h-2zM30 14h2v2h-2zM30 32h2v2h-2zM32 16h2v2h-2zM32 30h2v2h-2zM38 22h2v4h-2z" />
        </g>
        <g id="nid-patternfield3-f2">
          <path fill="var(--nid-accent-tertiary)" d="M4 18h2v2h-2zM4 28h2v2h-2zM8 14h2v2h-2zM8 32h2v2h-2zM14 8h2v2h-2zM14 14h2v2h-2zM14 32h2v2h-2zM14 38h2v2h-2zM16 18h2v2h-2zM16 28h2v2h-2zM18 4h2v2h-2zM18 16h2v2h-2zM18 30h2v2h-2zM18 42h2v2h-2zM28 4h2v2h-2zM28 16h2v2h-2zM28 30h2v2h-2zM28 42h2v2h-2zM30 18h2v2h-2zM30 28h2v2h-2zM32 8h2v2h-2zM32 14h2v2h-2zM32 32h2v2h-2zM32 38h2v2h-2zM38 14h2v2h-2zM38 32h2v2h-2zM42 18h2v2h-2zM42 28h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M2 6h2v2h-2zM2 40h2v2h-2zM4 4h2v2h-2zM4 42h2v2h-2zM6 2h2v2h-2zM6 44h2v2h-2zM14 22h2v4h-2zM18 20h2v2h-2zM18 26h2v2h-2zM20 18h2v2h-2zM20 28h2v2h-2zM22 14h4v2h-4zM22 32h4v2h-4zM26 18h2v2h-2zM26 28h2v2h-2zM28 20h2v2h-2zM28 26h2v2h-2zM32 22h2v4h-2zM40 2h2v2h-2zM40 44h2v2h-2zM42 4h2v2h-2zM42 42h2v2h-2zM44 6h2v2h-2zM44 40h2v2h-2z" />
          <path fill="var(--nid-accent-secondary)" d="M2 22h2v4h-2zM8 22h2v4h-2zM14 16h2v2h-2zM14 30h2v2h-2zM16 14h2v2h-2zM16 32h2v2h-2zM20 22h2v4h-2zM22 2h4v2h-4zM22 8h4v2h-4zM22 20h4v2h-4zM22 26h4v2h-4zM22 38h4v2h-4zM22 44h4v2h-4zM26 22h2v4h-2zM30 14h2v2h-2zM30 32h2v2h-2zM32 16h2v2h-2zM32 30h2v2h-2zM38 22h2v4h-2zM44 22h2v4h-2z" />
        </g>
        <g id="nid-patternfield3-f3">
          <path fill="var(--nid-accent-secondary)" d="M0 4h2v2h-2zM4 18h2v2h-2zM4 28h2v2h-2zM4 46h2v2h-2zM6 16h2v2h-2zM6 30h2v2h-2zM8 8h2v2h-2zM8 38h2v2h-2zM16 6h2v2h-2zM16 18h2v2h-2zM16 28h2v2h-2zM16 40h2v2h-2zM18 4h2v2h-2zM18 16h2v2h-2zM18 30h2v2h-2zM18 42h2v2h-2zM28 4h2v2h-2zM28 16h2v2h-2zM28 30h2v2h-2zM28 42h2v2h-2zM30 6h2v2h-2zM30 18h2v2h-2zM30 28h2v2h-2zM30 40h2v2h-2zM38 8h2v2h-2zM38 38h2v2h-2zM40 16h2v2h-2zM40 30h2v2h-2zM42 0h2v2h-2zM42 18h2v2h-2zM42 28h2v2h-2zM46 42h2v2h-2z" />
          <path fill="var(--nid-accent-quaternary)" d="M0 12h2v2h-2zM0 40h2v2h-2zM6 0h2v2h-2zM12 18h2v2h-2zM12 28h2v2h-2zM12 46h2v2h-2zM14 16h2v2h-2zM14 22h2v4h-2zM14 30h2v2h-2zM16 14h2v2h-2zM16 32h2v2h-2zM18 12h2v2h-2zM18 34h2v2h-2zM20 22h2v4h-2zM22 14h4v2h-4zM22 20h4v2h-4zM22 26h4v2h-4zM22 32h4v2h-4zM26 22h2v4h-2zM28 12h2v2h-2zM28 34h2v2h-2zM30 14h2v2h-2zM30 32h2v2h-2zM32 16h2v2h-2zM32 22h2v4h-2zM32 30h2v2h-2zM34 0h2v2h-2zM34 18h2v2h-2zM34 28h2v2h-2zM40 46h2v2h-2zM46 6h2v2h-2zM46 34h2v2h-2z" />
          <path fill="var(--nid-accent-tertiary)" d="M0 32h2v2h-2zM4 4h2v2h-2zM4 42h2v2h-2zM14 0h2v2h-2zM18 20h2v2h-2zM18 26h2v2h-2zM20 18h2v2h-2zM20 28h2v2h-2zM26 18h2v2h-2zM26 28h2v2h-2zM28 20h2v2h-2zM28 26h2v2h-2zM32 46h2v2h-2zM42 4h2v2h-2zM42 42h2v2h-2zM46 14h2v2h-2z" />
        </g>
      </defs>
        <g className="nid-pattern-unit" transform="translate(0 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 0)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 81)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 162)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(0 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(81 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(162 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
        <g className="nid-pattern-unit" transform="translate(243 243)">
          <rect width="81" height="81" fill="transparent" />
          <g transform="scale(1.6875)">
            <use href="#nid-patternfield3-f0" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f1" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f2" className="nid-pattern-frame" />
            <use href="#nid-patternfield3-f3" className="nid-pattern-frame" />
          </g>
        </g>
    </svg>
  );
}

export function PatternFieldAlumni({ className }: PatternFieldProps) {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 162 162"
      preserveAspectRatio="xMidYMid slice"
      className={className}
    >
      <defs>
        <pattern id="nid-patternfieldalumni" width="81" height="81" patternUnits="userSpaceOnUse">
          <g transform="scale(1.6875)">
        <path fill="var(--nid-accent-tertiary)" d="M4 4h2v2h-2zM18 4h2v2h-2zM28 4h2v2h-2zM42 4h2v2h-2zM16 6h2v2h-2zM30 6h2v2h-2zM14 8h2v2h-2zM32 8h2v2h-2zM8 14h2v2h-2zM23 14h2v2h-2zM38 14h2v2h-2zM6 16h2v2h-2zM40 16h2v2h-2zM4 18h2v2h-2zM20 18h2v2h-2zM26 18h2v2h-2zM42 18h2v2h-2zM18 20h2v2h-2zM22 20h4v2h-4zM28 20h2v2h-2zM20 22h2v4h-2zM26 22h2v4h-2zM14 23h2v2h-2zM32 23h2v2h-2zM18 26h2v2h-2zM22 26h4v2h-4zM28 26h2v2h-2zM4 28h2v2h-2zM20 28h2v2h-2zM26 28h2v2h-2zM42 28h2v2h-2zM6 30h2v2h-2zM40 30h2v2h-2zM8 32h2v2h-2zM23 32h2v2h-2zM38 32h2v2h-2zM14 38h2v2h-2zM32 38h2v2h-2zM16 40h2v2h-2zM30 40h2v2h-2zM4 42h2v2h-2zM18 42h2v2h-2zM28 42h2v2h-2zM42 42h2v2h-2z" />
        <path fill="var(--nid-accent-quaternary)" d="M20 6h2v2h-2zM26 6h2v2h-2zM8 8h2v2h-2zM22 8h4v2h-4zM38 8h2v2h-2zM6 20h2v2h-2zM40 20h2v2h-2zM8 22h2v4h-2zM38 22h2v4h-2zM6 26h2v2h-2zM40 26h2v2h-2zM8 38h2v2h-2zM22 38h4v2h-4zM38 38h2v2h-2zM20 40h2v2h-2zM26 40h2v2h-2z" />
        <path fill="var(--nid-accent-pentenary)" d="M16 14h2v2h-2zM30 14h2v2h-2zM14 16h2v2h-2zM18 16h2v2h-2zM28 16h2v2h-2zM32 16h2v2h-2zM16 18h2v2h-2zM30 18h2v2h-2zM16 28h2v2h-2zM30 28h2v2h-2zM14 30h2v2h-2zM18 30h2v2h-2zM28 30h2v2h-2zM32 30h2v2h-2zM16 32h2v2h-2zM30 32h2v2h-2z" />
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#nid-patternfieldalumni)" />
    </svg>
  );
}

export function PatternScatterAlumni({ className }: PatternFieldProps) {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 162 162"
      preserveAspectRatio="xMidYMid meet"
      className={className}
    >
      <path fill="var(--nid-accent-quaternary)" d="M27 0h3.375v3.375h-3.375zM30.38 0h3.375v3.375h-3.375zM128.25 0h3.375v3.375h-3.375zM131.63 0h3.375v3.375h-3.375zM27 3.37h3.375v3.375h-3.375zM131.63 3.37h3.375v3.375h-3.375zM27 6.75h3.375v3.375h-3.375zM33.75 6.75h3.375v3.375h-3.375zM124.88 6.75h3.375v3.375h-3.375zM131.63 6.75h3.375v3.375h-3.375zM0 27h3.375v3.375h-3.375zM3.38 27h3.375v3.375h-3.375zM6.75 27h3.375v3.375h-3.375zM151.88 27h3.375v3.375h-3.375zM155.25 27h3.375v3.375h-3.375zM158.62 27h3.375v3.375h-3.375zM0 30.38h3.375v3.375h-3.375zM158.62 30.38h3.375v3.375h-3.375zM6.75 33.75h3.375v3.375h-3.375zM151.88 33.75h3.375v3.375h-3.375zM6.75 124.87h3.375v3.375h-3.375zM151.88 124.87h3.375v3.375h-3.375zM0 128.25h3.375v3.375h-3.375zM158.62 128.25h3.375v3.375h-3.375zM0 131.63h3.375v3.375h-3.375zM3.38 131.63h3.375v3.375h-3.375zM6.75 131.63h3.375v3.375h-3.375zM151.88 131.63h3.375v3.375h-3.375zM155.25 131.63h3.375v3.375h-3.375zM158.62 131.63h3.375v3.375h-3.375zM27 151.88h3.375v3.375h-3.375zM33.75 151.88h3.375v3.375h-3.375zM124.88 151.88h3.375v3.375h-3.375zM131.63 151.88h3.375v3.375h-3.375zM27 155.25h3.375v3.375h-3.375zM131.63 155.25h3.375v3.375h-3.375zM27 158.63h3.375v3.375h-3.375zM30.38 158.63h3.375v3.375h-3.375zM128.25 158.63h3.375v3.375h-3.375zM131.63 158.63h3.375v3.375h-3.375z" />
      <path fill="var(--nid-accent-secondary)" d="M43.88 6.75h3.375v3.375h-3.375zM47.25 6.75h3.375v3.375h-3.375zM111.38 6.75h3.375v3.375h-3.375zM114.75 6.75h3.375v3.375h-3.375zM43.88 10.13h3.375v3.375h-3.375zM114.75 10.13h3.375v3.375h-3.375zM6.75 43.88h3.375v3.375h-3.375zM10.13 43.88h3.375v3.375h-3.375zM148.5 43.88h3.375v3.375h-3.375zM151.88 43.88h3.375v3.375h-3.375zM6.75 47.25h3.375v3.375h-3.375zM151.88 47.25h3.375v3.375h-3.375zM6.75 111.38h3.375v3.375h-3.375zM151.88 111.38h3.375v3.375h-3.375zM6.75 114.75h3.375v3.375h-3.375zM10.13 114.75h3.375v3.375h-3.375zM148.5 114.75h3.375v3.375h-3.375zM151.88 114.75h3.375v3.375h-3.375zM43.88 148.5h3.375v3.375h-3.375zM114.75 148.5h3.375v3.375h-3.375zM43.88 151.88h3.375v3.375h-3.375zM47.25 151.88h3.375v3.375h-3.375zM111.38 151.88h3.375v3.375h-3.375zM114.75 151.88h3.375v3.375h-3.375z" />
      <path fill="var(--nid-accent-tertiary)" d="M27 13.5h3.375v3.375h-3.375zM33.75 13.5h3.375v3.375h-3.375zM124.88 13.5h3.375v3.375h-3.375zM131.63 13.5h3.375v3.375h-3.375zM13.5 27h3.375v3.375h-3.375zM145.13 27h3.375v3.375h-3.375zM13.5 33.75h3.375v3.375h-3.375zM145.13 33.75h3.375v3.375h-3.375zM13.5 124.87h3.375v3.375h-3.375zM145.13 124.87h3.375v3.375h-3.375zM13.5 131.63h3.375v3.375h-3.375zM145.13 131.63h3.375v3.375h-3.375zM27 145.13h3.375v3.375h-3.375zM33.75 145.13h3.375v3.375h-3.375zM124.88 145.13h3.375v3.375h-3.375zM131.63 145.13h3.375v3.375h-3.375z" />
    </svg>
  );
}

export function PatternScatterPride({ className }: PatternFieldProps) {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 162 162"
      preserveAspectRatio="xMidYMid meet"
      className={className}
    >
      <path fill="var(--nid-accent-quaternary)" d="M33.75 13.5h3.375v3.375h-3.375zM40.5 13.5h3.375v3.375h-3.375zM118.12 13.5h3.375v3.375h-3.375zM124.88 13.5h3.375v3.375h-3.375zM40.5 16.88h3.375v3.375h-3.375zM118.12 16.88h3.375v3.375h-3.375zM33.75 20.25h3.375v3.375h-3.375zM124.88 20.25h3.375v3.375h-3.375zM13.5 33.75h3.375v3.375h-3.375zM20.25 33.75h3.375v3.375h-3.375zM138.37 33.75h3.375v3.375h-3.375zM145.13 33.75h3.375v3.375h-3.375zM13.5 40.5h3.375v3.375h-3.375zM16.87 40.5h3.375v3.375h-3.375zM141.75 40.5h3.375v3.375h-3.375zM145.13 40.5h3.375v3.375h-3.375zM13.5 118.13h3.375v3.375h-3.375zM16.87 118.13h3.375v3.375h-3.375zM141.75 118.13h3.375v3.375h-3.375zM145.13 118.13h3.375v3.375h-3.375zM13.5 124.87h3.375v3.375h-3.375zM20.25 124.87h3.375v3.375h-3.375zM138.37 124.87h3.375v3.375h-3.375zM145.13 124.87h3.375v3.375h-3.375zM33.75 138.38h3.375v3.375h-3.375zM124.88 138.38h3.375v3.375h-3.375zM40.5 141.75h3.375v3.375h-3.375zM118.12 141.75h3.375v3.375h-3.375zM33.75 145.13h3.375v3.375h-3.375zM40.5 145.13h3.375v3.375h-3.375zM118.12 145.13h3.375v3.375h-3.375zM124.88 145.13h3.375v3.375h-3.375z" />
      <path fill="var(--nid-accent-tertiary)" d="M60.75 3.37h3.375v3.375h-3.375zM97.87 3.37h3.375v3.375h-3.375zM67.5 6.75h3.375v3.375h-3.375zM91.13 6.75h3.375v3.375h-3.375zM64.13 10.13h3.375v3.375h-3.375zM94.5 10.13h3.375v3.375h-3.375zM3.38 60.75h3.375v3.375h-3.375zM155.25 60.75h3.375v3.375h-3.375zM10.13 64.13h3.375v3.375h-3.375zM148.5 64.13h3.375v3.375h-3.375zM6.75 67.5h3.375v3.375h-3.375zM151.88 67.5h3.375v3.375h-3.375zM6.75 91.13h3.375v3.375h-3.375zM151.88 91.13h3.375v3.375h-3.375zM10.13 94.5h3.375v3.375h-3.375zM148.5 94.5h3.375v3.375h-3.375zM3.38 97.88h3.375v3.375h-3.375zM155.25 97.88h3.375v3.375h-3.375zM64.13 148.5h3.375v3.375h-3.375zM94.5 148.5h3.375v3.375h-3.375zM67.5 151.88h3.375v3.375h-3.375zM91.13 151.88h3.375v3.375h-3.375zM60.75 155.25h3.375v3.375h-3.375zM97.87 155.25h3.375v3.375h-3.375z" />
      <path fill="var(--nid-accent-pentenary)" d="M30.38 23.62h3.375v3.375h-3.375zM128.25 23.62h3.375v3.375h-3.375zM23.63 30.38h3.375v3.375h-3.375zM135 30.38h3.375v3.375h-3.375zM23.63 128.25h3.375v3.375h-3.375zM135 128.25h3.375v3.375h-3.375zM30.38 135h3.375v3.375h-3.375zM128.25 135h3.375v3.375h-3.375z" />
    </svg>
  );
}
