// GENERATED by scripts/generate-patterns.py - do not edit by hand.
// Regenerate with `npm run generate:patterns`.
//
// The three craft pattern fields of the home bento, rebuilt from the Figma Make
// export (design/reference/home-figma-make/). Each is one 24x24-cell unit -
// four 12x12 quadrants pinwheeled 0/90/180/-90 - repeated by an SVG <pattern>.
//
// In the export these three tiles are 25,454 lines of absolutely positioned
// <div>s, 76% of the whole file, because every unit is spelled out. They are
// identical, so one unit is enough. Emitting them as <pattern> also makes the
// field fluid rather than a fixed 4x4 of 81px units.
//
// Fills are semantic accent tokens, so the fields re-theme with the page and
// invert with appearance - a thing the export's baked hexes cannot do. They are
// decorative and aria-hidden, so the decorative ramp is allowed (CLAUDE.md
// § Colour).

export interface PatternFieldProps {
  className?: string;
}

export function PatternField1({ className }: PatternFieldProps) {
  return (
    <svg aria-hidden="true" className={className}>
      <defs>
        <pattern id="nid-patternfield1" width="81" height="81" patternUnits="userSpaceOnUse">
          <g transform="scale(1.6875)">
        <path fill="var(--nid-accent-quaternary)" d="M22 2h2v2h-2zM24 4h2v2h-2zM32 4h2v2h-2zM30 6h2v2h-2zM28 8h2v2h-2zM4 14h2v2h-2zM6 16h2v2h-2zM8 18h2v2h-2zM22 20h4v2h-4zM4 22h2v2h-2zM20 22h2v4h-2zM26 22h2v4h-2zM44 22h2v2h-2zM2 24h2v2h-2zM42 24h2v2h-2zM22 26h4v2h-4zM38 28h2v2h-2zM40 30h2v2h-2zM42 32h2v2h-2zM18 38h2v2h-2zM16 40h2v2h-2zM14 42h2v2h-2zM22 42h2v2h-2zM24 44h2v2h-2z" />
        <path fill="var(--nid-accent-tertiary)" d="M34 2h2v2h-2zM36 8h2v2h-2zM8 10h2v2h-2zM26 10h2v2h-2zM2 12h2v2h-2zM20 16h2v2h-2zM18 18h2v2h-2zM28 18h2v2h-2zM10 20h2v2h-2zM30 20h2v2h-2zM16 26h2v2h-2zM36 26h2v2h-2zM18 28h2v2h-2zM28 28h2v2h-2zM26 30h2v2h-2zM44 34h2v2h-2zM20 36h2v2h-2zM38 36h2v2h-2zM10 38h2v2h-2zM12 44h2v2h-2z" />
        <path fill="var(--nid-accent-secondary)" d="M20 4h2v2h-2zM22 6h2v2h-2zM24 12h2v2h-2zM22 14h2v2h-2zM42 20h2v2h-2zM12 22h2v2h-2zM32 22h2v2h-2zM40 22h2v2h-2zM6 24h2v2h-2zM14 24h2v2h-2zM34 24h2v2h-2zM4 26h2v2h-2zM24 32h2v2h-2zM22 34h2v2h-2zM24 40h2v2h-2zM26 42h2v2h-2z" />
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#nid-patternfield1)" />
    </svg>
  );
}

export function PatternField2({ className }: PatternFieldProps) {
  return (
    <svg aria-hidden="true" className={className}>
      <defs>
        <pattern id="nid-patternfield2" width="81" height="81" patternUnits="userSpaceOnUse">
          <g transform="scale(1.6875)">
        <path fill="var(--nid-accent-tertiary)" d="M0 0h2v2h-2zM46 0h2v2h-2zM20 2h2v2h-2zM26 2h2v2h-2zM4 4h2v2h-2zM42 4h2v2h-2zM6 6h2v2h-2zM40 6h2v2h-2zM14 8h2v2h-2zM32 8h2v2h-2zM16 10h2v2h-2zM30 10h2v2h-2zM8 14h2v2h-2zM38 14h2v2h-2zM10 16h2v2h-2zM16 16h2v2h-2zM30 16h2v2h-2zM36 16h2v2h-2zM18 18h2v2h-2zM28 18h2v2h-2zM2 20h2v2h-2zM44 20h2v2h-2zM22 22h4v4h-4zM2 26h2v2h-2zM44 26h2v2h-2zM18 28h2v2h-2zM28 28h2v2h-2zM10 30h2v2h-2zM16 30h2v2h-2zM30 30h2v2h-2zM36 30h2v2h-2zM8 32h2v2h-2zM38 32h2v2h-2zM16 36h2v2h-2zM30 36h2v2h-2zM14 38h2v2h-2zM32 38h2v2h-2zM6 40h2v2h-2zM40 40h2v2h-2zM4 42h2v2h-2zM42 42h2v2h-2zM20 44h2v2h-2zM26 44h2v2h-2zM0 46h2v2h-2zM46 46h2v2h-2z" />
        <path fill="var(--nid-accent-quaternary)" d="M22 0h2v2h-2zM6 2h2v2h-2zM44 6h2v2h-2zM18 8h2v2h-2zM20 10h2v2h-2zM34 10h2v2h-2zM10 12h2v2h-2zM18 14h2v2h-2zM32 18h2v2h-2zM38 18h2v2h-2zM36 20h2v2h-2zM46 22h2v2h-2zM0 24h2v2h-2zM10 26h2v2h-2zM8 28h2v2h-2zM14 28h2v2h-2zM28 32h2v2h-2zM36 34h2v2h-2zM12 36h2v2h-2zM26 36h2v2h-2zM28 38h2v2h-2zM2 40h2v2h-2zM40 44h2v2h-2zM24 46h2v2h-2z" />
        <path fill="var(--nid-accent-secondary)" d="M24 0h2v2h-2zM40 2h2v2h-2zM2 6h2v2h-2zM28 8h2v2h-2zM12 10h2v2h-2zM26 10h2v2h-2zM36 12h2v2h-2zM28 14h2v2h-2zM8 18h2v2h-2zM14 18h2v2h-2zM10 20h2v2h-2zM0 22h2v2h-2zM46 24h2v2h-2zM36 26h2v2h-2zM32 28h2v2h-2zM38 28h2v2h-2zM18 32h2v2h-2zM10 34h2v2h-2zM20 36h2v2h-2zM34 36h2v2h-2zM18 38h2v2h-2zM44 40h2v2h-2zM6 44h2v2h-2zM22 46h2v2h-2z" />
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#nid-patternfield2)" />
    </svg>
  );
}

export function PatternField3({ className }: PatternFieldProps) {
  return (
    <svg aria-hidden="true" className={className}>
      <defs>
        <pattern id="nid-patternfield3" width="81" height="81" patternUnits="userSpaceOnUse">
          <g transform="scale(1.6875)">
        <path fill="var(--nid-accent-secondary)" d="M18 4h2v2h-2zM28 4h2v2h-2zM16 6h2v2h-2zM30 6h2v2h-2zM8 8h2v2h-2zM14 8h2v2h-2zM32 8h2v2h-2zM38 8h2v2h-2zM8 14h2v2h-2zM38 14h2v2h-2zM6 16h2v2h-2zM18 16h2v2h-2zM28 16h2v2h-2zM40 16h2v2h-2zM4 18h2v2h-2zM16 18h2v2h-2zM30 18h2v2h-2zM42 18h2v2h-2zM4 28h2v2h-2zM16 28h2v2h-2zM30 28h2v2h-2zM42 28h2v2h-2zM6 30h2v2h-2zM18 30h2v2h-2zM28 30h2v2h-2zM40 30h2v2h-2zM8 32h2v2h-2zM38 32h2v2h-2zM8 38h2v2h-2zM14 38h2v2h-2zM32 38h2v2h-2zM38 38h2v2h-2zM16 40h2v2h-2zM30 40h2v2h-2zM18 42h2v2h-2zM28 42h2v2h-2z" />
        <path fill="var(--nid-accent-tertiary)" d="M4 4h2v2h-2zM42 4h2v2h-2zM20 6h2v2h-2zM26 6h2v2h-2zM20 18h2v2h-2zM26 18h2v2h-2zM6 20h2v2h-2zM18 20h2v2h-2zM28 20h2v2h-2zM40 20h2v2h-2zM6 26h2v2h-2zM18 26h2v2h-2zM28 26h2v2h-2zM40 26h2v2h-2zM20 28h2v2h-2zM26 28h2v2h-2zM20 40h2v2h-2zM26 40h2v2h-2zM4 42h2v2h-2zM42 42h2v2h-2z" />
        <path fill="var(--nid-accent-quaternary)" d="M22 8h4v2h-4zM16 14h2v2h-2zM23 14h2v2h-2zM30 14h2v2h-2zM14 16h2v2h-2zM32 16h2v2h-2zM22 20h4v2h-4zM8 22h2v4h-2zM20 22h2v4h-2zM26 22h2v4h-2zM38 22h2v4h-2zM14 23h2v2h-2zM32 23h2v2h-2zM22 26h4v2h-4zM14 30h2v2h-2zM32 30h2v2h-2zM16 32h2v2h-2zM23 32h2v2h-2zM30 32h2v2h-2zM22 38h4v2h-4z" />
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#nid-patternfield3)" />
    </svg>
  );
}

export function PatternFieldAlumni({ className }: PatternFieldProps) {
  return (
    <svg aria-hidden="true" className={className}>
      <defs>
        <pattern id="nid-patternfieldalumni" width="81" height="81" patternUnits="userSpaceOnUse">
          <g transform="scale(1.6875)">
        <path fill="var(--nid-accent-tertiary)" d="M4 4h2v2h-2zM18 4h2v2h-2zM28 4h2v2h-2zM42 4h2v2h-2zM16 6h2v2h-2zM30 6h2v2h-2zM14 8h2v2h-2zM32 8h2v2h-2zM8 14h2v2h-2zM23 14h2v2h-2zM38 14h2v2h-2zM6 16h2v2h-2zM40 16h2v2h-2zM4 18h2v2h-2zM20 18h2v2h-2zM26 18h2v2h-2zM42 18h2v2h-2zM18 20h2v2h-2zM22 20h4v2h-4zM28 20h2v2h-2zM20 22h2v4h-2zM26 22h2v4h-2zM14 23h2v2h-2zM32 23h2v2h-2zM18 26h2v2h-2zM22 26h4v2h-4zM28 26h2v2h-2zM4 28h2v2h-2zM20 28h2v2h-2zM26 28h2v2h-2zM42 28h2v2h-2zM6 30h2v2h-2zM40 30h2v2h-2zM8 32h2v2h-2zM23 32h2v2h-2zM38 32h2v2h-2zM14 38h2v2h-2zM32 38h2v2h-2zM16 40h2v2h-2zM30 40h2v2h-2zM4 42h2v2h-2zM18 42h2v2h-2zM28 42h2v2h-2zM42 42h2v2h-2z" />
        <path fill="var(--nid-accent-quaternary)" d="M20 6h2v2h-2zM26 6h2v2h-2zM8 8h2v2h-2zM22 8h4v2h-4zM38 8h2v2h-2zM6 20h2v2h-2zM40 20h2v2h-2zM8 22h2v4h-2zM38 22h2v4h-2zM6 26h2v2h-2zM40 26h2v2h-2zM8 38h2v2h-2zM22 38h4v2h-4zM38 38h2v2h-2zM20 40h2v2h-2zM26 40h2v2h-2z" />
        <path fill="var(--nid-accent-pentenary)" d="M16 14h2v2h-2zM30 14h2v2h-2zM14 16h2v2h-2zM18 16h2v2h-2zM28 16h2v2h-2zM32 16h2v2h-2zM16 18h2v2h-2zM30 18h2v2h-2zM16 28h2v2h-2zM30 28h2v2h-2zM14 30h2v2h-2zM18 30h2v2h-2zM28 30h2v2h-2zM32 30h2v2h-2zM16 32h2v2h-2zM30 32h2v2h-2z" />
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#nid-patternfieldalumni)" />
    </svg>
  );
}
