#!/usr/bin/env python3
"""Emit the home-page craft pattern fields as SVG <pattern> components.

Source : design/assets/patterns/home-patterns.json
Output : src/components/home/patterns.tsx

The JSON holds each tiled field as one 24x24-cell unit already merged into
maximal rectangles per colour, and each scatter field as loose cells at design
size. It was extracted once from the Figma Make export of the Home frame
(Figma node 3031:50673), which has since been removed from the repo - now that
the Figma MCP is available, re-derive from Figma if a pattern changes and
update the JSON rather than editing patterns.tsx.

Colours in the JSON are the design hexes. They are mapped to semantic accent
tokens here, through the peacock ramp in themes.css, so the fields re-theme
and invert with appearance.

Run with: npm run generate:patterns
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "design", "assets", "patterns", "home-patterns.json")
OUT = os.path.join(ROOT, "src", "components", "home", "patterns.tsx")
THEMES_CSS = os.path.join(ROOT, "src", "styles", "themes.css")

# Same preference order as scripts/generate-motifs.py.
SEMANTIC_BY_PRIMITIVE = [
    ("accent-primary", "primary-450"),
    ("accent-secondary", "secondary-350"),
    ("accent-tertiary", "tertiary-300"),
    ("accent-quaternary", "quaternary-250"),
    ("accent-pentenary", "pentenary-300"),
    ("accent-subtle", "primary-150"),
    ("accent-muted", "primary-350"),
    ("accent-strong", "primary-550"),
]


def peacock_ramp():
    css = open(THEMES_CSS, encoding="utf-8").read()
    m = re.search(r':root,\s*\[data-theme="peacock"\]\s*\{([^}]*)\}', css)
    ramp = {}
    for fam, step, hexv in re.findall(
        r"--nid-(\w+)-(\d+):\s*(#[0-9A-Fa-f]{6})", m.group(1)
    ):
        ramp.setdefault(hexv.lower(), []).append(f"{fam}-{step}")
    return ramp


def token_for(hexv, ramp, warnings):
    primitives = ramp.get(hexv, [])
    for semantic, primitive in SEMANTIC_BY_PRIMITIVE:
        if primitive in primitives:
            return f"var(--nid-{semantic})"
    warnings.append(f"  {hexv} -> {primitives or 'UNKNOWN'} (no layer-2 token)")
    return f"var(--nid-{primitives[0]})" if primitives else None


def main():
    data = json.load(open(SOURCE, encoding="utf-8"))
    ramp = peacock_ramp()
    warnings = []
    components = []

    unit_cells = data["unitCells"]
    # The unit is 81 CSS px across (two 12-cell quadrants of 3.375px cells),
    # drawn on a unit_cells grid, so the paths are scaled by 81/unit_cells.
    # Getting this wrong renders the field at grid scale - visibly too dense.
    unit_px = data["cell"] * 12 * 2
    scale = unit_px / unit_cells

    for field in data["fields"]:
        label = field["label"]
        by_colour = field["rects"]
        paths = []
        for colour, boxes in sorted(by_colour.items(), key=lambda kv: -len(kv[1])):
            fill = token_for(colour, ramp, warnings)
            d = "".join(f"M{x} {y}h{w}v{h}h-{w}z" for x, y, w, h in boxes)
            paths.append(f'        <path fill="{fill}" d="{d}" />')

        pid = f"nid-{label.lower()}"
        components.append(f'''
export function {label}({{ className }}: PatternFieldProps) {{
  return (
    <svg aria-hidden="true" className={{className}}>
      <defs>
        <pattern id="{pid}" width="{unit_px:g}" height="{unit_px:g}" patternUnits="userSpaceOnUse">
          <g transform="scale({scale:g})">
{chr(10).join(paths)}
          </g>
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#{pid})" />
    </svg>
  );
}}''')
        print(f"  {label:14} {sum(len(v) for v in by_colour.values()):3} rects, "
              f"{len(by_colour)} colours")

    for scatter in data["scatters"]:
        label, edge, by_colour = scatter["label"], scatter["edge"], scatter["cells"]
        paths = []
        for colour, boxes in sorted(by_colour.items(), key=lambda kv: -len(kv[1])):
            fill = token_for(colour, ramp, warnings)
            d = "".join(f"M{x:g} {y:g}h{w:g}v{w:g}h-{w:g}z" for x, y, w in boxes)
            paths.append(f'      <path fill="{fill}" d="{d}" />')

        components.append(f'''
export function {label}({{ className }}: PatternFieldProps) {{
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 {edge} {edge}"
      preserveAspectRatio="xMidYMid meet"
      className={{className}}
    >
{chr(10).join(paths)}
    </svg>
  );
}}''')
        print(f"  {label:14} {sum(len(v) for v in by_colour.values()):3} scattered cells, "
              f"{len(by_colour)} colours")

    header = '''// GENERATED by scripts/generate-patterns.py - do not edit by hand.
// Regenerate with `npm run generate:patterns`; the source is
// design/assets/patterns/home-patterns.json.
//
// The craft pattern fields of the home bento. Each tiled field is one
// 24x24-cell unit - four 12x12 quadrants pinwheeled 0/90/180/-90 - repeated by
// an SVG <pattern>, so the field is fluid rather than a fixed 4x4 of 81px units.
//
// Scatter fields (PatternScatter*) are the exception: loose cells with no
// repeating unit, emitted at their design size.
//
// Fills are semantic accent tokens, so the fields re-theme with the page and
// invert with appearance. They are decorative and aria-hidden, so the
// decorative ramp is allowed (CLAUDE.md § Colour).

export interface PatternFieldProps {
  className?: string;
}
'''
    open(OUT, "w", encoding="utf-8").write(header + "\n".join(components) + "\n")

    if warnings:
        print("\nprimitive fallbacks:")
        print("\n".join(sorted(set(warnings))))
    print(f"\ngenerate-patterns: wrote {len(components)} fields to {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
